name: Merge CI

on:
  push:
    branches: [master]

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Merge Files
        run: |
          mkdir dist
          touch dist/main.user.js
          cp README.md dist
          cp right-box.html dist
          cat SCRIPT_HEADER.js > dist/main.user.js
          cat libraries/* >> dist/main.user.js
          cat main.js >> dist/main.user.js

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
